// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaBibliotecario.App.Persistencia;

namespace SistemaBibliotecario.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SistemaBibliotecario.App.Dominio.Entidades.Autor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("aut_nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("SistemaBibliotecario.App.Dominio.Entidades.Bibliotecario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("bib_apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bib_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bib_identificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bib_nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bib_telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("bib_turnBib")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Bibliotecarios");
                });

            modelBuilder.Entity("SistemaBibliotecario.App.Dominio.Entidades.Editorial", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("edit_nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Editoriales");
                });

            modelBuilder.Entity("SistemaBibliotecario.App.Dominio.Entidades.Ejemplar", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ejem_estEjem")
                        .HasColumnType("int");

                    b.Property<int?>("ejem_libid")
                        .HasColumnType("int");

                    b.Property<string>("ejem_scdd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("ejem_libid");

                    b.ToTable("Ejemplares");
                });

            modelBuilder.Entity("SistemaBibliotecario.App.Dominio.Entidades.Libro", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("lib_autid")
                        .HasColumnType("int");

                    b.Property<int>("lib_catLibro")
                        .HasColumnType("int");

                    b.Property<int?>("lib_editid")
                        .HasColumnType("int");

                    b.Property<DateTime>("lib_fechaPub")
                        .HasColumnType("datetime2");

                    b.Property<int>("lib_idioLibro")
                        .HasColumnType("int");

                    b.Property<string>("lib_isbn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("lib_numCapt")
                        .HasColumnType("int");

                    b.Property<int>("lib_numPag")
                        .HasColumnType("int");

                    b.Property<string>("lib_sinopsis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("lib_tipoLibro")
                        .HasColumnType("int");

                    b.Property<string>("lib_titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("lib_autid");

                    b.HasIndex("lib_editid");

                    b.ToTable("Libros");
                });

            modelBuilder.Entity("SistemaBibliotecario.App.Dominio.Entidades.Reserva", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("reser_bibid")
                        .HasColumnType("int");

                    b.Property<int>("reser_diasPrest")
                        .HasColumnType("int");

                    b.Property<int?>("reser_ejemid")
                        .HasColumnType("int");

                    b.Property<DateTime>("reser_fechDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("reser_fechReserva")
                        .HasColumnType("datetime2");

                    b.Property<float>("reser_multa")
                        .HasColumnType("real");

                    b.Property<int?>("reser_usuid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("reser_bibid");

                    b.HasIndex("reser_ejemid");

                    b.HasIndex("reser_usuid");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("SistemaBibliotecario.App.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("usu_apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usu_direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usu_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usu_identificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usu_nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usu_telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaBibliotecario.App.Dominio.Entidades.Ejemplar", b =>
                {
                    b.HasOne("SistemaBibliotecario.App.Dominio.Entidades.Libro", "ejem_lib")
                        .WithMany()
                        .HasForeignKey("ejem_libid");

                    b.Navigation("ejem_lib");
                });

            modelBuilder.Entity("SistemaBibliotecario.App.Dominio.Entidades.Libro", b =>
                {
                    b.HasOne("SistemaBibliotecario.App.Dominio.Entidades.Autor", "lib_aut")
                        .WithMany()
                        .HasForeignKey("lib_autid");

                    b.HasOne("SistemaBibliotecario.App.Dominio.Entidades.Editorial", "lib_edit")
                        .WithMany()
                        .HasForeignKey("lib_editid");

                    b.Navigation("lib_aut");

                    b.Navigation("lib_edit");
                });

            modelBuilder.Entity("SistemaBibliotecario.App.Dominio.Entidades.Reserva", b =>
                {
                    b.HasOne("SistemaBibliotecario.App.Dominio.Entidades.Bibliotecario", "reser_bib")
                        .WithMany()
                        .HasForeignKey("reser_bibid");

                    b.HasOne("SistemaBibliotecario.App.Dominio.Entidades.Ejemplar", "reser_ejem")
                        .WithMany()
                        .HasForeignKey("reser_ejemid");

                    b.HasOne("SistemaBibliotecario.App.Dominio.Entidades.Usuario", "reser_usu")
                        .WithMany()
                        .HasForeignKey("reser_usuid");

                    b.Navigation("reser_bib");

                    b.Navigation("reser_ejem");

                    b.Navigation("reser_usu");
                });
#pragma warning restore 612, 618
        }
    }
}
